// Copyright 2017-2021 @foxone/dev authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @foxone/dev, do not edit

export const packageInfo = { name: "@foxone/dev", version: "1.0.0" };
